
services:
    mongo:
        image: mongo:latest
        restart: unless-stopped
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - app-network
        # environment:
        #    MONGO_INITDB_ROOT_USERNAME: admin
        #    MONGO_INITDB_ROOT_PASSWORD: my_password
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express:latest
        restart: unless-stopped
        container_name: mongo-express
        ports:
            - 8081:8081
        # environment:
        #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        #     ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
        #     ME_CONFIG_MONGODB_URL: mongodb://admin:my_password@mongo:27017/

    webapp:
        build: .
        restart: unless-stopped
        container_name: wifi_app
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        networks:
            - app-network


networks:
  app-network:
    driver: bridge

volumes:
    mongo_data:

