swagger: "2.0"
info:
  title: My API
  version: 1.0.0
paths:
  /data:
    get:
      summary: Пример endpoint
      parameters:
        - name: name
          in: path
          type: string
          required: true
          description: Имя пользователя
      responses:
        200:
          description: Приветственное сообщение
          schema:
            type: object
            properties:
              message:
                type: string